# Questions

```{r library}
#| echo: false
#| message: false
#| warning: false

library(here)
library(dplyr)
library(ggplot2)
library(NatParksPalettes)
```

```{r read-data}
#| echo: false
#| message: false

responses <- readRDS(here("data/responses.rds"))
```

```{r get-questions}
#| echo: false
#| message: false

# Get df of questions
questions_df <- responses %>%
  select(QUESTION_NUMBER, QUESTION_TEXT) %>%
  arrange(QUESTION_NUMBER) %>%
  distinct(QUESTION_NUMBER, .keep_all = TRUE)
```

```{r iterate-questions}
#| eval: false
#| echo: false
#| results: asis

for (i in questions_df$QUESTION_NUMBER) {
  # Extract the current question
  current_question <- questions_df %>%
    filter(QUESTION_NUMBER == i)

  # Create the H2 header dynamically
  cat(
    "\n## ",
    current_question$QUESTION_NUMBER,
    ": ",
    current_question$QUESTION_TEXT,
    "\n\n",
    sep = ""
  )

  # Filter responses for a single question
  question_responses <- responses %>%
    filter(QUESTION_NUMBER == current_question$QUESTION_NUMBER)

  # Histogram of responses by program type
  p <- ggplot(question_responses, aes(x = RESPONSE, fill = RESPONSE)) +
    geom_bar(show.legend = FALSE) +
    scale_fill_manual(values = natparks.pals("KingsCanyon", 6)) +
    facet_grid(~PROGRAMTYPE_NAME)
  print(p)

  cat(" \n ", sep = "")
}
```

